# Generated by Django 3.2.7 on 2024-01-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
